import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import DataLoader from "./components/DataLoader";
import ClientEvents from "./components/ClientEvents";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
	weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} antialiased`}>
				<DataLoader />
				<ClientEvents />
				<main className="p-2.5">{children}</main>
			</body>
		</html>
	);
}
