import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // добавили Roboto
import "./globals.css";
import PreloaderProvider from "./components/PreloaderProvider";
import ClientEvents from "./components/ClientEvents";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
	weight: ["400", "500", "700"], // нужные начертания
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} antialiased`}>
				<PreloaderProvider>
					<ClientEvents />
					<main className="p-2.5">{children}</main>
				</PreloaderProvider>
			</body>
		</html>
	);
}
